# Generated by Django 3.0.7 on 2020-07-09 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinataire', models.BooleanField(blank=True)),
                ('id_destinataire', models.IntegerField(blank=True)),
                ('commentateur', models.BooleanField(blank=True)),
                ('commentaire', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_eleve', models.CharField(max_length=100)),
                ('prenom_eleve', models.CharField(max_length=100)),
                ('num_tel_eleve', models.CharField(blank=True, max_length=100)),
                ('adresse_eleve', models.CharField(max_length=255)),
                ('date_naissance_eleve', models.DateField(blank=True)),
                ('nationalite_eleve', models.CharField(max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='profils_eleves/')),
                ('matricule', models.CharField(blank=True, max_length=100)),
                ('status_scolarite', models.BooleanField(blank=True)),
                ('reste_a_payer', models.IntegerField(blank=True, default=0)),
                ('classe', models.ManyToManyField(related_name='eleve', to='gestionnaire.Classe')),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_enseignant', models.CharField(max_length=100)),
                ('prenom_enseignant', models.CharField(max_length=100)),
                ('adresse_enseignant', models.CharField(max_length=255)),
                ('num_tel_enseignant', models.CharField(blank=True, max_length=100)),
                ('date_naissance_enseignant', models.DateField(blank=True)),
                ('email_enseignant', models.EmailField(blank=True, max_length=254)),
                ('autre_profession', models.CharField(blank=True, max_length=100)),
                ('nationalite_enseignant', models.CharField(max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('login', models.CharField(blank=True, max_length=100)),
                ('mdp', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='profils_enseignants/')),
                ('antecedant_judiciaire', models.TextField(blank=True)),
                ('ancienne_profession', models.CharField(blank=True, max_length=100)),
                ('salaire', models.IntegerField(blank=True)),
                ('periode', models.CharField(blank=True, max_length=100)),
                ('regularite', models.BooleanField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupe', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matiere', models.CharField(max_length=20)),
                ('groupe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.Groupe')),
            ],
        ),
        migrations.CreateModel(
            name='Niveau',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_parent', models.CharField(max_length=100)),
                ('prenom_parent', models.CharField(max_length=100)),
                ('adresse_parent', models.CharField(max_length=255)),
                ('num_tel_parent', models.CharField(blank=True, max_length=100)),
                ('email_parent', models.EmailField(blank=True, max_length=254)),
                ('profession', models.CharField(max_length=100)),
                ('nationalite_parent', models.CharField(max_length=100)),
                ('lien_de_parente', models.CharField(max_length=100)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('antecedant_judiciaire', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='profils_parents/')),
                ('situation_financiere', models.CharField(blank=True, max_length=100)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.Eleve')),
                ('utilisateur', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField(blank=True)),
                ('remarque', models.CharField(blank=True, max_length=255)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.Eleve')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.Enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.Matiere')),
            ],
        ),
        migrations.CreateModel(
            name='MoyenneGenerale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_generale', models.IntegerField(blank=True)),
                ('remarque', models.CharField(blank=True, max_length=255)),
                ('decision', models.CharField(blank=True, max_length=100)),
                ('eleve', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.Eleve')),
                ('enseignant_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.Enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='Moyenne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.IntegerField(blank=True)),
                ('remarque', models.CharField(blank=True, max_length=255)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.Eleve')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.Enseignant')),
                ('matiere', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.Matiere')),
            ],
        ),
        migrations.AddField(
            model_name='enseignant',
            name='groupe',
            field=models.ManyToManyField(related_name='enseignant', to='gestionnaire.Groupe'),
        ),
        migrations.AddField(
            model_name='classe',
            name='groupe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.Groupe'),
        ),
        migrations.AddField(
            model_name='classe',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.Niveau'),
        ),
    ]
