# Generated by Django 3.0.7 on 2020-08-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0003_auto_20200810_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='coefficient',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
