# Generated by Django 3.0.7 on 2020-11-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0005_enseignant_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='matiere',
            field=models.ManyToManyField(related_name='classe', to='gestionnaire.Matiere'),
        ),
        migrations.AddField(
            model_name='eleve',
            name='matiere',
            field=models.ManyToManyField(related_name='eleve', to='gestionnaire.Matiere'),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matiere',
            field=models.ManyToManyField(related_name='enseignant', to='gestionnaire.Matiere'),
        ),
        migrations.AlterField(
            model_name='matiere',
            name='matiere',
            field=models.CharField(max_length=50),
        ),
    ]
