# Generated by Django 3.0.7 on 2020-11-12 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0006_auto_20201112_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleve',
            name='matiere',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='matiere',
        ),
    ]
