# Generated by Django 3.0.7 on 2020-11-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0008_remove_classe_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='matiere',
            field=models.ManyToManyField(related_name='classe', to='gestionnaire.Matiere'),
        ),
    ]
