# Generated by Django 3.0.7 on 2020-11-12 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestionnaire', '0009_classe_matiere'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classe',
            name='matiere',
        ),
    ]
