# Generated by Django 3.0.7 on 2020-11-12 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestionnaire', '0006_auto_20201112_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moyenne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne', models.FloatField()),
                ('remarque', models.CharField(blank=True, max_length=255)),
                ('commentaire', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField()),
                ('remarque', models.CharField(blank=True, max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.Eleve')),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.Enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.Matiere')),
                ('moyenne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moyenne.Moyenne')),
            ],
        ),
        migrations.CreateModel(
            name='MoyenneGenerale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moyenne_generale', models.FloatField()),
                ('remarque', models.CharField(blank=True, max_length=255)),
                ('commentaire', models.TextField(blank=True)),
                ('decision', models.CharField(max_length=100)),
                ('annee_scolaire', models.CharField(max_length=20)),
                ('periode', models.CharField(choices=[('premier_semestre', 'Premier Semestre'), ('deuxieme_semestre', 'Deuxieme Semestre'), ('premier_trimestre', 'Premier Trimestre'), ('deuxieme_trimestre', 'Deuxieme Trimestre'), ('troixieme_trimestre', 'Troixieme Trimestre')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('enseignant_principal', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gestionnaire.Enseignant')),
            ],
        ),
        migrations.AddField(
            model_name='moyenne',
            name='moyenne_generale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moyenne.MoyenneGenerale'),
        ),
    ]
